### ISSUE TITLE
Issue starting the editor 

### ISSUE THREAD

**Issue by skyelondon18** [mike19283/RainbowZ-Editor#4]
I've been trying to load my rom into the editor and every time i try it tells me that its an invalid file, why is that ??

**Comment by mike19283** [comment]
What does it say, exactly? It says different things depending on the problem

**Comment by mike19283** [comment]
Ohh. Ok. You aren't using a 1.0 version of dkc

**Comment by mike19283** [comment]
Easy fix. You aren't using a 1.0 version of the game

**Comment by skyelondon18** [comment]
oh ok sweet thanks!
