### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by diegofilis** [mike19283/RainbowZ-Editor#5]
I would like to translate the game into Portuguese, but it would be necessary to add some special characters. Would it be possible to add them?
á ã â é ê í ó õ ô ç

**Comment by mike19283** [comment]
Sadly, no. Those characters were never added to the base game, so adding functionality in my editor would do nothing for the game. These are the only characters the game supports. 
![image](https://github.com/mike19283/RainbowZ-Editor/assets/23127751/7f640159-fb5b-4570-83d6-0a809df8c867)
